# Generated by Django 4.1.2 on 2022-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, verbose_name='apellido'),
        ),
    ]
