# Generated by Django 3.2.8 on 2022-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='nombre'),
        ),
    ]
