# Generated by Django 4.1.2 on 2022-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='slogan',
            field=models.CharField(max_length=85, null=True),
        ),
    ]
