# Generated by Django 3.2.8 on 2022-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cédula',
            field=models.IntegerField(unique=True),
        ),
    ]
