# Generated by Django 4.1.2 on 2022-11-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_candidate_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cédula',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
