# Generated by Django 4.1.2 on 2022-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_voter_cédula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cédula',
            field=models.PositiveIntegerField(unique = True),
        ),
    ]
