# Generated by Django 4.1.2 on 2022-11-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voter_cédula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='cédula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
